"""add account actions

Revision ID: 13f27f331fae
Revises: c70e03eb010a
Create Date: 2026-03-26 10:57:21.460768

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "13f27f331fae"
down_revision: str | Sequence[str] | None = "c70e03eb010a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_actions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("action_type", sa.String(length=128), nullable=False),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_account_actions_account_id"),
        "account_actions",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_account_actions_action_type"),
        "account_actions",
        ["action_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_account_actions_created_at"),
        "account_actions",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_account_actions_created_at"), table_name="account_actions")
    op.drop_index(op.f("ix_account_actions_action_type"), table_name="account_actions")
    op.drop_index(op.f("ix_account_actions_account_id"), table_name="account_actions")
    op.drop_table("account_actions")
    # ### end Alembic commands ###
