"""initial schema

Revision ID: c70e03eb010a
Revises: 
Create Date: 2026-03-25 15:02:13.565876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c70e03eb010a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('firebase_local_id', sa.String(length=255), nullable=True),
    sa.Column('firebase_id_token', sa.Text(), nullable=True),
    sa.Column('firebase_refresh_token', sa.Text(), nullable=True),
    sa.Column('svgmaker_auth_token_id', sa.Text(), nullable=True),
    sa.Column('svgmaker_auth_token_refresh', sa.Text(), nullable=True),
    sa.Column('svgmaker_auth_token_sig', sa.Text(), nullable=True),
    sa.Column('credits_last_known', sa.Integer(), nullable=True),
    sa.Column('last_generation_at', sa.DateTime(), nullable=True),
    sa.Column('last_refreshed_at', sa.DateTime(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_email'), 'accounts', ['email'], unique=True)
    op.create_index(op.f('ix_accounts_firebase_local_id'), 'accounts', ['firebase_local_id'], unique=False)
    op.create_index(op.f('ix_accounts_status'), 'accounts', ['status'], unique=False)
    op.create_table('generation_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_generation_id', sa.String(length=255), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('quality', sa.String(length=64), nullable=False),
    sa.Column('aspect_ratio', sa.String(length=64), nullable=False),
    sa.Column('background', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('credit_cost', sa.Integer(), nullable=True),
    sa.Column('svg_url', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_requests_account_id'), 'generation_requests', ['account_id'], unique=False)
    op.create_index(op.f('ix_generation_requests_external_generation_id'), 'generation_requests', ['external_generation_id'], unique=True)
    op.create_index(op.f('ix_generation_requests_status'), 'generation_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generation_requests_status'), table_name='generation_requests')
    op.drop_index(op.f('ix_generation_requests_external_generation_id'), table_name='generation_requests')
    op.drop_index(op.f('ix_generation_requests_account_id'), table_name='generation_requests')
    op.drop_table('generation_requests')
    op.drop_index(op.f('ix_accounts_status'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_firebase_local_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_email'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
