"""add telegram bot tables

Revision ID: f56fe2bf5f2a
Revises: 13f27f331fae
Create Date: 2026-03-26 11:52:58.362243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f56fe2bf5f2a'
down_revision: Union[str, Sequence[str], None] = '13f27f331fae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_invite_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('code_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_invite_codes_code'), 'telegram_invite_codes', ['code'], unique=True)
    op.create_index(op.f('ix_telegram_invite_codes_code_type'), 'telegram_invite_codes', ['code_type'], unique=False)
    op.create_table('telegram_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('quota_remaining', sa.Integer(), nullable=False),
    sa.Column('initial_grant_applied', sa.Boolean(), nullable=False),
    sa.Column('last_daily_grant_on', sa.Date(), nullable=True),
    sa.Column('last_generation_at', sa.DateTime(), nullable=True),
    sa.Column('started_with_code', sa.String(length=128), nullable=True),
    sa.Column('is_unlimited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_users_telegram_user_id'), 'telegram_users', ['telegram_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_users_telegram_user_id'), table_name='telegram_users')
    op.drop_table('telegram_users')
    op.drop_index(op.f('ix_telegram_invite_codes_code_type'), table_name='telegram_invite_codes')
    op.drop_index(op.f('ix_telegram_invite_codes_code'), table_name='telegram_invite_codes')
    op.drop_table('telegram_invite_codes')
    # ### end Alembic commands ###
